### ISSUE TITLE
Z Endstop Rework Needed

### ISSUE THREAD

**Issue by 3dGriff** [Hooklet3d/OdinOne#36]
The Z end stop needs to be adjusted so that the 2020 fastening bolt may be accessed from the front of the machine.  This will allow for easier Z Level adjustment.  

Additionally, due to the DuPont connection being loose, we need to add a channel that fits and holds the DuPont sleeve in place and prevents unwanted loosening.

**Comment by BotleHewer** [comment]
Reworked File uploaded
