### ISSUE TITLE
Extruder Wire Length 

### ISSUE THREAD

**Issue by BotleHewer** [Hooklet3d/OdinOne#51]
Length of Nema extruder wires need to be increased by at least 25cm to accommodate moving main board off PSU.

See img for reference.
![img_20170219_151858](https://cloud.githubusercontent.com/assets/9956363/23106895/16560e96-f6ba-11e6-8bfb-edc41219f6cc.jpg)

Consider moving extruder assembly wire path to either next to(or attached to) Y endstop mount. Or possibly to left cross beam end (similar to pre-mentos Odin One build).

**Comment by 3dGriff** [comment]
#46

**Comment by 3dGriff** [comment]
The initial cable lengths for the X, Y, Z axis are 70cm.  The length for the Extruder cable is 100cm providing full vertical movement.
