### ISSUE TITLE
PSU Spool Mount design.

### ISSUE THREAD

**Issue by BotleHewer** [Hooklet3d/OdinOne#53]
Design a spool mount mod for the psu for MK1 design.
This should/could include mounting of PTFE tube intake to top cross beam.

This will not necessarily ship with production, but will be available on github mod collections.

** Note to @BotleHewer merge current PTFE tube PSU mount, with current 3d printed table mount(or something similar)

**Comment by 3dGriff** [comment]
@BotleHewer any progress on this?

**Comment by BotleHewer** [comment]
@3dGriff not at this time. current system working ok.

**Comment by 3dGriff** [comment]
Closed due to inactivity
