### ISSUE TITLE
Draft Fan Guard Dim Incorrect

### ISSUE THREAD

**Issue by 3dGriff** [Hooklet3d/OdinOne#55]
Scale of fan guard for draft fan is not correct 75c33fd2c480100437d8873ee7598ae6496d191b . Working issue now

**Comment by 3dGriff** [comment]
These should be relatively close at this point but it needs verification.

**Comment by J-Skepp** [comment]
Fan guard 75c33fd has been printed and verified.

**Comment by 3dGriff** [comment]
@J-Skepp I noticed it still might be too large, did you also test for fit?  Could be wrong.

**Comment by 3dGriff** [comment]
closed due to inactivity
