### ISSUE TITLE
Blower Fan Duct not solid

### ISSUE THREAD

**Issue by BotleHewer** [Hooklet3d/OdinOne#58]
Fan duct design for blower fan (https://github.com/Hooklet3d/OdinOne/blob/Mentos_RC/Parts/OdinOne/Mods/Active_Cooling/MK8_DraftCooler/Fan_Duct_DraftCoolerMK8.stl) is not solid. Causing issues in S3d where it tries to bridge a solid floor mid way up part. see screen cap.
![capture](https://cloud.githubusercontent.com/assets/9956363/24170915/798d7776-0e50-11e7-9588-8805d874a3b0.JPG)

Attempt to fix by making solid in Meshmixer.

**Comment by BotleHewer** [comment]
Part run through make solid and commuted to MC #3a03137.

Slicing Verified in S3D. Print test to follow

**Comment by 3dGriff** [comment]
@BotleHewer I just added a duct with an altered angle, check out the file in commit 92b1064c5126dc025e64072dadda26c2cc1ede12 I think it's best to just fix it now if you could.

Be aware of the slight indentation at the top of the duct (the part that attaches to the fan) this was added to provide a tighter fit and make sure the duct does not fall off during printing.

**Comment by BotleHewer** [comment]
@3dGriff  It appears above issues are not present in latest version of duct.

S3D verified.  Will be printing shortly.

Issue can be closed IMO

**Comment by 3dGriff** [comment]
@BotleHewer that's good to know, as a heads up your nozzle may be slightly higher or lower than the current machine, verify dimension and positioning with that in mind.
