### ISSUE TITLE
Sainsmart Mockup

### ISSUE THREAD

**Issue by J-Skepp** [Hooklet3d/OdinOne#59]
I'm throwing this mock-up of the 2in1 up just for reference.  Don't know where it should go. 
It can use more detail or get deleted.  Either way.
Throw the virtual board  in the virtual case and see if the virtual screw holes line up.  
G'night

**Comment by 3dGriff** [comment]
@J-Skepp Awesome, I'll make a directory called 'jigs', submit the part a s a pull request.

**Comment by 3dGriff** [comment]
commit 75f33d18618071bb835931385f79e774474fa6b8
