### ISSUE TITLE
Talking points

### ISSUE THREAD

**Issue by BotleHewer** [Hooklet3d/OdinOne#60]
A place to collect talking points for Tradeshows, and promotional materials.

**Comment by BotleHewer** [comment]
+ Each kit does this before it's boxed
![2111753667806508171-account_id 1](https://cloud.githubusercontent.com/assets/9956363/24324634/ef0aeec0-1157-11e7-86ab-8a041f89abe3.jpg)

+ And gets it's specific calibrated firmware flashed

**Comment by 3dGriff** [comment]
@BotleHewer please move this issue to the marketing 17 repo.  https://github.com/Hooklet3d/Marketing_17  

This should be reserved for issues specific to the Odin One from a development standpoint.  

Thanks.

**Comment by BotleHewer** [comment]
@3dGriff issue recreated in marketing.
ok to close

**Comment by 3dGriff** [comment]
Moved and closed
