### ISSUE TITLE
Test C-Duct Cooler

### ISSUE THREAD

**Issue by BotleHewer** [Hooklet3d/OdinOne#63]
Need to test & Evaluate C-style cooling.
![img_20170331_011601](https://cloud.githubusercontent.com/assets/9956363/24538666/41aecd2a-15b0-11e7-99c1-f9c64c92b3c1.jpg)
![img_20170331_011606](https://cloud.githubusercontent.com/assets/9956363/24538669/445a54cc-15b0-11e7-8027-1dd74b3f87d6.jpg)
![img_20170331_011612](https://cloud.githubusercontent.com/assets/9956363/24538671/4475dd96-15b0-11e7-83ef-25eb3aed40e6.jpg)
![img_20170331_011556](https://cloud.githubusercontent.com/assets/9956363/24538672/4487277c-15b0-11e7-870c-e90ddf104807.jpg)

**Comment by BotleHewer** [comment]
Created and uploaded an alternate version of the Duct that doesn't circle the nozzle as far, but is lighter, smaller, should print without support(at least with active cooling on printer) and gives better visibility on the nozzle.

**Comment by BotleHewer** [comment]
What I'm seeing so far is that the angle of the duct still needs adjustment. Cooling is still reducing temp on hotend significantly.  

I'm liking the design on V3 better than v2, so I'll attempt to rework the angle of the airflow to miss the nozzle.

**Comment by 3dGriff** [comment]
Hey just had a machine free up to test on this, I had a question for you.

In slicing it looks like the mesh of the guard doesn't start until layer 3, screenshot included shows tool paths at layer 2.  Is this part of your design? 

<img width="731" alt="screen shot 2017-03-31 at 4 51 17 pm" src="https://cloud.githubusercontent.com/assets/21249940/24570690/878d5668-1632-11e7-8740-b77339edf266.png">

**Comment by BotleHewer** [comment]
@3dGriff  that is a glitch in the design. I just looked at it and the hex grid was not flush as I though it was.
Will upload a fixed file in a sec

**Comment by 3dGriff** [comment]
@BotleHewer as you mentioned the v3 wasn't quite right dimensions wise, I am currently testing the v4 version (current as of this post) it looks good thus for.

Have you thought about or tested moving the duct closer to the nozzle for more direct cooling?

**Comment by 3dGriff** [comment]
@BotleHewer I ran three test prints, the first with the v4 duct and the last with the existing draft cooler.  The difference can be seen in 90 degree bridging.  


![img_20170407_073641](https://cloud.githubusercontent.com/assets/21249940/24800384/85d91388-1b65-11e7-8503-242ca2856b2c.jpg)

The last print I did as a comparison, this print has the same slicer settings as the first two and used the existing cooler.  

![img_20170407_073654](https://cloud.githubusercontent.com/assets/21249940/24800414/a7cfb0d2-1b65-11e7-9ff2-561217dedf4e.jpg)

From my understanding the A8 style cooler's (and those similar) flaw is that they try to distribute the air over a greater distance thus limiting the overall airflow.  As I mentioned before, I really think the duct needs to be closer to the nozzle.  As it stands I believe the duct is delivering indirect cooling.  

I think another thing to consider is that the fan is blowing cool (relative) air into a heated space.  The area around the hot end has a constant updraft—this immediately forces the cooling air upward.  Given the distance and likely diminished airflow, it's unlikely the cooler is making much of a difference.  The ideal cooler needs to consolidate its air to the smallest point possible (ideally just below the nozzle) at no point do we want to cool the entire part or large areas of the part (this can lead to warping issues).  I think it can be done with this duct style it just needs to be worked out. 

The design is solid and it looks great, we just need to make it a more functional cooler.  I hope this helps, let me know if you have any questions.

**Comment by 3dGriff** [comment]
@BotleHewer I was able to resolve this in slicer settings (the bridging issue) however, I am noticing an issue on one machine.  On the machine in question, running the fan over 60% impacts the extruder temp to the point of triggering the thermal protection.  

I believe we need to dial in the focus of the airflow.

**Comment by BotleHewer** [comment]
@3dGriff As far as the temp issue: the v4 should be angled to alleviate this, as it was an issue with the v3 duct. I'm curious why it's only effecting 1 of your bots, as I'm not having that issue on mine either with the v4 duct.

I'll work on moving the duct closer still to the nozzle, I hope to have a design ready to print later today.

**Comment by BotleHewer** [comment]
@3dGriff, @J-Skepp I'm for scrapping the c-duct line of study. Unless objections from anyone else I suggest closing this ticket.
Will open a new ticket for the straight duct currently being dev.

**Comment by 3dGriff** [comment]
@BotleHewer sounds good, I'll remove and update

**Comment by 3dGriff** [comment]
Removed in commit baa9d49a1612829164a56751edcb19507baee9b8 

Closing issue
